name: Build and Deploy APIService

on:
  push:
    branches:
      - main
    paths:
      - 'finAPI/**'
      - '.github/workflows/buildapiservice.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./finAPI
          file: ./finAPI/Dockerfile
          push: true
          tags: ${{secrets.API_DOCKER_IMAGE_TAG}}
          args: |
            PYTHON_VERSION=3.8.15
      - name: Deploy Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            sudo apt-get update && sudo apt-get install -y docker-compose
            sudo wget -O ${{secrets.API_COMPOSE_FILE_NAME}} -q ${{secrets.COMPOSE_FILE_GIT_PATH}}
            sudo docker stop $(sudo docker ps -aq --filter ancestor=${{secrets.API_DOCKER_IMAGE_TAG}})
            sudo docker-compose pull
            sudo docker-compose up -d
