name: Build and Deploy APIService

on:
  push:
    branches:
      - main
    paths:
      - 'finAPI/**'
      - '.github/workflows/buildapiservice.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate with gcloud
        uses: google-github-actions/auth@v1.0.0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: |
            ${{ secrets.GCP_CREDENTIALS }}
          project_id: monoservice
          skip_install: true

          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./finAPI
          file: ./finAPI/Dockerfile
          push: true
          tags: ${{secrets.API_DOCKER_IMAGE_TAG}}
          args: |
            PYTHON_VERSION=3.8.15
          env: |
            CA_BUNDLE_CRT: ${{ secrets.CA_BUNDLE_CRT }}
            CERTIFICATE_CRT: ${{ secrets.CERTIFICATE_CRT }}
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: micromeshcloudrun
          image: ${{secrets.API_DOCKER_IMAGE_TAG}}
          region: europe-west1
          platform: managed
          memory: 256Mi
          concurrency: 80
          max_instances: 5
