name: Build and Deploy React App

on:
  push:
    branches:
      - main
    paths:
      - 'hostApp/**'
      - '.github/workflows/buildhostapp.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        working-directory: ./hostApp
        run: npm install

      - name: Set environment variables
        env:
          FIN_API_URL: ${{ secrets.FIN_API_URL }}
          SHOWCASE_URL: ${{ secrets.SHOWCASE_URL }}
          ONBOARDING_URL: ${{ secrets.ONBOARDING_URL }}
        run: |
          echo "FIN_API_URL=${FIN_API_URL}" >> ./hostApp/.env
          echo "REACT_APP_SHOWCASE_URL=${SHOWCASE_URL}" >> ./hostApp/.env
          echo "REACT_APP_ONBOARDING_URL=${ONBOARDING_URL}" >> ./hostApp/.env


      - name: Build React app
        working-directory: ./hostApp
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: ./hostApp/build
